### ISSUE TITLE
ESP32 Compatibility

### ISSUE THREAD

**Issue by CoreProduction** [CoreElectronics/CE-PiicoDev-Unified#7]
We'd like to make PiicoDev available for ESP32! I'm putting out the call for help and a bounty (to be negotiated offline) that will likely take the form of a generous store credit on [Core Electronics](https://core-electronics.com.au/)

This probably requires a profile to be added to `PiicoDev_Unified.py`
This *definitely* requires a check that each PiicoDev module works on the new hardware.

I'm putting out the call to anybody that wants to make a PR for  `PiicoDev_Unified.py` to include the new board compatibility.

Currently the `I2CUnifiedMachine(I2CBase)` class assumes to be running on a RPi Pico and so selects appropriate default pins.
Perhaps this class could be modified or reused to support the ESP32.

I've created a branch `dev-esp32` to manage this project on - as we go I'll update the following list.

PiicoDev modules that have been demonstrated to work with ESP32 as of the latest commit to the `dev-esp32` branch:

**Updated compatibility list**

- [x] [Atmospheric Sensor BME280](https://core-electronics.com.au/piicodev-atmospheric-sensor-bme280.html)
- [x] [Magnetometer QMC6310](https://core-electronics.com.au/piicodev-magnetometer-qmc6310.html)
- [x] [Colour Sensor VEML6040](https://core-electronics.com.au/piicodev-colour-sensor-veml6040.html)
- [x] [Ambient Light Sensor VEML6030](https://core-electronics.com.au/piicodev-ambient-light-sensor-veml6030.html)
- [x] [Pressure Sensor MS5637](https://core-electronics.com.au/piicodev-pressure-sensor-ms5637.html)
- [x] [Precision Temperature Sensor TMP117](https://core-electronics.com.au/piicodev-precision-temperature-sensor-tmp117.html)
- [x] [Air Quality Sensor ENS160](https://core-electronics.com.au/piicodev-air-quality-sensor-ens160.html)
- [x] [3-Axis Accelerometer LIS3DH](https://core-electronics.com.au/piicodev-3-axis-accelerometer-lis3dh.html)
- [x] [Laser Distance Sensor VL53L1X](https://core-electronics.com.au/piicodev-laser-distance-sensor-vl53l1x.html)
- [x] [Real Time Clock (RTC) RV3028](https://core-electronics.com.au/piicodev-real-time-clock-rv3028.html)
- [x] [Button](https://core-electronics.com.au/piicodev-button.html)
- [x] [Capacitive Touch Sensor](https://core-electronics.com.au/piicodev-capacitive-touch-sensor.html)
- [x] [Potentiometer (Rotary)](https://core-electronics.com.au/piicodev-potentiometer-rotary.html)
- [x] [Potentiometer (Slide)](https://core-electronics.com.au/piicodev-slide-potentiometer.html)
- [x] [Servo Driver (4 Channel)](https://core-electronics.com.au/piicodev-servo-driver.html)
- [x] [OLED Display Module (128x64)](https://core-electronics.com.au/piicodev-oled-display-module-128x64-ssd1306.html)
- [x] [3x RGB LED Module](https://core-electronics.com.au/piicodev-3x-rgb-led-module.html)
- [x] [Buzzer Module](https://core-electronics.com.au/piicodev-buzzer-module.html)
- [x] [Transceiver 915MHz](https://core-electronics.com.au/piicodev-transceiver-915mhz.html)
- [x] [RFID Module (NFC 13.56MHz)](https://core-electronics.com.au/piicodev-rfid-module.html)

**Comment by LiamHowell** [comment]
Awesome! I've started working through this issue.

**Comment by LiamHowell** [comment]
Tested with the [ESP32 ](https://core-electronics.com.au/tinypico-47708.html)

Dont have modules on hand
- [ ]  [Colour Sensor VEML6040](https://core-electronics.com.au/piicodev-colour-sensor-veml6040.html)
- [ ]  [Button](https://core-electronics.com.au/piicodev-button.html)
- [ ]  [Potentiometer (Slide)](https://core-electronics.com.au/piicodev-slide-potentiometer.html)
- [ ]  [Potentiometer (Rotary)](https://core-electronics.com.au/piicodev-potentiometer-rotary.html)
- [ ]  [Real Time Clock (RTC) RV3028](https://core-electronics.com.au/piicodev-real-time-clock-rv3028.html)
- [ ]  [Servo Driver (4 Channel)](https://core-electronics.com.au/piicodev-servo-driver.html)

Tested and confirmed reading/writing 
- [x]  [Atmospheric Sensor BME280](https://core-electronics.com.au/piicodev-atmospheric-sensor-bme280.html)
- [x]  [Magnetometer QMC6310](https://core-electronics.com.au/piicodev-magnetometer-qmc6310.html)
- [x]  [Ambient Light Sensor VEML6030](https://core-electronics.com.au/piicodev-ambient-light-sensor-veml6030.html)
- [x]  [Pressure Sensor MS5637](https://core-electronics.com.au/piicodev-pressure-sensor-ms5637.html)
- [x]  [Precision Temperature Sensor TMP117](https://core-electronics.com.au/piicodev-precision-temperature-sensor-tmp117.html)
- [x]  [Air Quality Sensor ENS160](https://core-electronics.com.au/piicodev-air-quality-sensor-ens160.html)
- [x]  [3-Axis Accelerometer LIS3DH](https://core-electronics.com.au/piicodev-3-axis-accelerometer-lis3dh.html)
- [x]  [Laser Distance Sensor VL53L1X](https://core-electronics.com.au/piicodev-laser-distance-sensor-vl53l1x.html)
- [x]  [Capacitive Touch Sensor](https://core-electronics.com.au/piicodev-capacitive-touch-sensor.html)
- [x]  [OLED Display Module (128x64)](https://core-electronics.com.au/piicodev-oled-display-module-128x64-ssd1306.html)
- [x]  [3x RGB LED Module](https://core-electronics.com.au/piicodev-3x-rgb-led-module.html)
- [x]  [Buzzer Module](https://core-electronics.com.au/piicodev-buzzer-module.html)
- [x]  [Transceiver 915MHz](https://core-electronics.com.au/piicodev-transceiver-915mhz.html)
- [x]  [RFID Module (NFC 13.56MHz)](https://core-electronics.com.au/piicodev-rfid-module.html)

All working on [C3](https://core-electronics.com.au/esp32-c3-wroom-development-board.html), [S2](https://core-electronics.com.au/esp32-s2-saola-1r-dev-kit-featuring-esp32-s2-wrover.html), [S3 ](https://core-electronics.com.au/esp32-s3-devkitc-1-n8-esp32-s3-wroom-1-dev-board-8mb-flash.html)(Commented out Radio module due to lack of memory, haven't explored why this error was caused)

**Comment by LiamHowell** [comment]
All modules confirmed working!!

Tested with the [ESP32 ](https://core-electronics.com.au/tinypico-47708.html), [C3](https://core-electronics.com.au/esp32-c3-wroom-development-board.html), [S2](https://core-electronics.com.au/esp32-s2-saola-1r-dev-kit-featuring-esp32-s2-wrover.html), [S3 ](https://core-electronics.com.au/esp32-s3-devkitc-1-n8-esp32-s3-wroom-1-dev-board-8mb-flash.html). 

With the settings: 
bus=0
freq = 100000 (default PiicoDev)( The S2 and ESP32 (base) were run at 400+kHz passing all tests)


Tested and confirmed reading/writing 
- [x]  [Colour Sensor VEML6040](https://core-electronics.com.au/piicodev-colour-sensor-veml6040.html)
- [x]  [Button](https://core-electronics.com.au/piicodev-button.html)
- [x]  [Potentiometer (Slide)](https://core-electronics.com.au/piicodev-slide-potentiometer.html)
- [x]  [Potentiometer (Rotary)](https://core-electronics.com.au/piicodev-potentiometer-rotary.html)
- [x]  [Real Time Clock (RTC) RV3028](https://core-electronics.com.au/piicodev-real-time-clock-rv3028.html)
- [x]  [Servo Driver (4 Channel)](https://core-electronics.com.au/piicodev-servo-driver.html)
- [x]  [Atmospheric Sensor BME280](https://core-electronics.com.au/piicodev-atmospheric-sensor-bme280.html)
- [x]  [Magnetometer QMC6310](https://core-electronics.com.au/piicodev-magnetometer-qmc6310.html)
- [x]  [Ambient Light Sensor VEML6030](https://core-electronics.com.au/piicodev-ambient-light-sensor-veml6030.html)
- [x]  [Pressure Sensor MS5637](https://core-electronics.com.au/piicodev-pressure-sensor-ms5637.html)
- [x]  [Precision Temperature Sensor TMP117](https://core-electronics.com.au/piicodev-precision-temperature-sensor-tmp117.html)
- [x]  [Air Quality Sensor ENS160](https://core-electronics.com.au/piicodev-air-quality-sensor-ens160.html)
- [x]  [3-Axis Accelerometer LIS3DH](https://core-electronics.com.au/piicodev-3-axis-accelerometer-lis3dh.html)
- [x]  [Laser Distance Sensor VL53L1X](https://core-electronics.com.au/piicodev-laser-distance-sensor-vl53l1x.html)
- [x]  [Capacitive Touch Sensor](https://core-electronics.com.au/piicodev-capacitive-touch-sensor.html)
- [x]  [OLED Display Module (128x64)](https://core-electronics.com.au/piicodev-oled-display-module-128x64-ssd1306.html)
- [x]  [3x RGB LED Module](https://core-electronics.com.au/piicodev-3x-rgb-led-module.html)
- [x]  [Buzzer Module](https://core-electronics.com.au/piicodev-buzzer-module.html)
- [x]  [Transceiver 915MHz](https://core-electronics.com.au/piicodev-transceiver-915mhz.html)
- [x]  [RFID Module (NFC 13.56MHz)](https://core-electronics.com.au/piicodev-rfid-module.html)

**Comment by CoreProduction** [comment]
Nice work Liam! We'll close this as addressed in PR https://github.com/CoreElectronics/CE-PiicoDev-Unified/pull/11
